### ISSUE TITLE
Previewing activities hangs JClic Author

### ISSUE THREAD

**Issue by leoperbo** [projectestac/jclic#11]
Working on Ubuntu 14.04 with Oracle Java 7, when I click on "preview" button in JClic Author (jclic-0.2.3.4.zip version released on 2013-12-13), it hangs and I have to kill Java. The only way to test activities is open the projects in JClic Player.

Same version is working well on Windows.

**Comment by frncesc** [comment]
I'm unable to reproduce the issue.

This is a screenshot of JClic Author running on my Ubuntu 14.04 32 bit (updated from official sources, current kernel 3.13.0-55), with Unity desktop and Oracle Java 1.7.0_80 installed from [ppa:webupd8team/java](https://launchpad.net/~webupd8team/+archive/ubuntu/java)

The play preview window opens and closes without problems.

![jclic author in ubuntu 14 04 with oracle java 7](https://cloud.githubusercontent.com/assets/1183816/8494147/73a02296-2162-11e5-8e03-4852af1c2f7b.png)

Please try again installing JClic from [ppa:jclic/master](https://launchpad.net/~jclic/+archive/ubuntu/master)

If the problem persists, please provide information about what desktop are you using (Unity, Gnome, Gnome Classic, KDE, LXDE...)

Also, try launching JClicAuthor from a console and report the messages shown, if any. To do so, just open a terminal (`Ctrl`+`Alt`+`T`) and write: `jclicauthor` (assuming you have installed JClic from [ppa:jclic/master](https://launchpad.net/~jclic/+archive/ubuntu/master))

**Comment by leoperbo** [comment]
Thank's for the reply. 

I'm on Ubuntu 14.04 64 bit (updated from official sources, current kernel 3.13.0-57-generic - amd64), Unity Desktop and same version of Java (Oracle Java 1.7.0_80 installed from ppa:webupd8team/java):

![captura de pantalla de 2015-07-03 08 35 17](https://cloud.githubusercontent.com/assets/13077338/8500352/f54c7ac6-2160-11e5-8007-658a0e07197a.png)

This is the output in terminal when I run jclicauthor from decompressed [zip version released on 2013-12-13](https://launchpad.net/jclic/trunk/0.2.3.4/+download/jclic-0.2.3.4.zip):

```
~$ java -jar /home/mysuer/software/jclic-0.2.3.4/jclicauthor.jar
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
jul 03, 2015 8:31:13 AM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush system prefs: java.util.prefs.BackingStoreException: /etc/.java/.systemPrefs/edu create failed.
```
When I run jclicauthor installed from ppa:jclic/master, the problem persist (jclicauthor hangs when I try to preview an activity). This is the output in this case:

```
~$ jclicauthor
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at javax.swing.plaf.synth.SynthLookAndFeel.paintRegion(SynthLookAndFeel.java:371)
	at javax.swing.plaf.synth.SynthLookAndFeel.update(SynthLookAndFeel.java:335)
	at javax.swing.plaf.synth.SynthRootPaneUI.update(SynthRootPaneUI.java:120)
	at javax.swing.JComponent.paintComponent(JComponent.java:779)
	at javax.swing.JComponent.paint(JComponent.java:1055)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5232)
	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:295)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1249)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5180)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4991)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:808)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:796)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:796)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:769)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:718)
	at javax.swing.RepaintManager.access$1100(RepaintManager.java:62)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1677)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by leoperbo** [comment]
Sorry, sorry, sorry!

I just realized that the preview window have been working ok, but have been located in another workspace! The "hang" I had detected was the preview window stopping me to use the work window of jclicauthor:

![captura de pantalla de 2015-07-03 12 01 38](https://cloud.githubusercontent.com/assets/13077338/8502909/29da621a-217c-11e5-9501-dcd14e9577e4.png)

By the way, the output in terminal was clean when I changed the look and feel to "default":
![captura de pantalla de 2015-07-03 12 10 02](https://cloud.githubusercontent.com/assets/13077338/8502941/a5a3b734-217c-11e5-9a74-93b90f135305.png)
